# Generated by Django 2.0.2 on 2018-05-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logowanie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=3000)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('grade', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('region', models.CharField(blank=True, max_length=30)),
                ('postalCode', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('homeNumber', models.IntegerField()),
                ('apartmentNumber', models.IntegerField(blank=True)),
                ('PESEL', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logowanie.Student'),
        ),
    ]
