# Generated by Django 2.0.2 on 2018-05-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logowanie', '0002_auto_20180523_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logowanie.Student')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logowanie.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SinglePayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True)),
                ('price', models.IntegerField()),
                ('paymentID', models.CharField(max_length=50)),
                ('paymentHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logowanie.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='solution',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homework',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='homework',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
