# Generated by Django 2.0.2 on 2018-05-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logowanie', '0003_auto_20180525_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleGrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='singlepayment',
            name='paymentHistory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logowanie.PaymentHistory'),
        ),
        migrations.RenameModel(
            old_name='Grades',
            new_name='StudentsGrades',
        ),
        migrations.AddField(
            model_name='singlegrade',
            name='StudentsGrades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logowanie.StudentsGrades'),
        ),
    ]
