# Generated by Django 2.0.2 on 2018-05-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logowanie', '0004_auto_20180525_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logowanie.Student')),
                ('adminStatus', models.CharField(max_length=20)),
            ],
            bases=('logowanie.student',),
        ),
    ]
