# Generated by Django 2.0.2 on 2018-05-25 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logowanie', '0006_auto_20180525_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacherProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logowanie.Admin'),
        ),
    ]
