# Generated by Django 2.0.2 on 2018-05-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logowanie', '0007_auto_20180525_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacherProfile',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='logowanie.Student'),
        ),
    ]
